<template>
    <div class="p-1">
        <CKCardList 
            :title="title" 
            :show-filter="true" 
            :show-add="false"
            :filterFormCode="filterFormCode"
            :filterEndPoint="filterEndPoint"
            :pagination="pagination"
            @page-change="handlePageChange">
            <template #header-actions>
                <UButton :href="urlPDF" download label="PDF" leadingIcon="lucide:file" />
                <UButton :href="urlCSV" label="CSV" download leading-icon="lucide:file-spreadsheet"/>
            </template>
            <UTable :loading="loading" :data="data" :columns="columns">
                <template #loading>
                    <CKLoader />
                </template>
                <template #empty>
                    <UError :error="{ statusMessage: error || 'No Record Found!!' }" />
                </template>
                <template #action-cell>
                    <CKEdit />
                </template>
            </UTable>
        </CKCardList>
    </div>
</template>

<script setup>
import CKCardList from "~/components/common/CKCardList.vue"
import CKLoader from "~/components/common/CKLoader.vue"
import CKEdit from "~/components/common/CKEdit.vue"

definePageMeta({
    layout: 'home'
})

const { $axios } = useNuxtApp()

const loading = ref(false)
const error = ref(null)
const data = ref([])
const pagination = ref(null)
const pageSize = ref(50)
const urlPDF = ref("")
const urlCSV = ref("")

const title = "GRN Register"
const filterFormCode = "grn_register_filter"
const filterEndPoint = "/form/defaultForm"

const columns = [
    { accessorKey: 'po_number', header: 'PO Number' },
    { accessorKey: 'po_date', header: 'PO Date' },
    { accessorKey: 'vendor', header: 'Vendor' },
    { accessorKey: 'generated_by', header: 'Generated by' },
    { accessorKey: 'type', header: 'Type' },
    { accessorKey: 'approval', header: 'Approval' },
    { id: 'action'}
]

const loadForm = async (page = 1, limit = 50) => {
    loading.value = true
    try {
        const dataSchema = {
            po_number: 'TEXT',
            po_date: 'DATE',
            vendor: 'TEXT',
            generated_by: 'TEXT',
            type: 'TEXT',
            approval: 'TEXT',
        }
        
        const result = await $axios.post('/form/dummy', { 
            schema: dataSchema,
            quantity: 5000,
            page,
            limit
        })
        
        data.value = result.data?.result?.data || []
        pagination.value = result.data?.result?.pagination || null
        urlPDF.value = useRuntimeConfig().public.apiBase + `${filterEndPoint}?output=PDF`;
        urlCSV.value = useRuntimeConfig().public.apiBase + `${filterEndPoint}?output=CSV`;
    } catch (err) {
        error.value = err.response?.data?.message || err.message || 'Failed to load data'
        console.error('Error loading GRN register:', err)
    } finally {
        loading.value = false
    }
}

const handlePageChange = (page) => {
    if (page && typeof page === 'number') {
        loadForm(page, pageSize.value)
    }
}

onMounted(loadForm)
</script>

