<!-- status: Waiting/Done, uhid, patient_name, services, time_reg, time_in, time_out  -->
<template>
    <div class="p-1">
        <!-- PO Register Table -->
        <CKCardList 
            :title="title" 
            :show-filter="true" 
            :show-add="false"
            :filterFormCode="filterFormCode"
            :filterEndPoint="filterEndPoint">
            <UTable :loading="loading" :data="data" :columns="columns">
                <template #loading>
                    <CKLoader />
                </template>
                <template #empty>
                    <UError :error="{ statusMessage: error || 'No Record Found!!' }" />
                </template>
                <template #action-cell="{ row }">
                    <div class="flex gap-1 ">
                        <CKEdit />
                        <CKGenerateGRN  />
                        <CKPrintPO  />
                    </div>
                </template>
            </UTable>
        </CKCardList>
    </div>
</template>

<script setup>
import CKCardList from "~/components/common/CKCardList.vue"
import CKLoader from "~/components/common/CKLoader.vue"
import CKEdit from "~/components/common/CKEdit.vue"
import CKGenerateGRN from "~/components/common/CKGenerateGRN.vue"
import CKPrintPO from "~/components/common/CKPrintPO.vue"

definePageMeta({
    layout: 'home'
})

// State
const loading = ref(false)
const error = ref(null)
const title = "PO Register"
const { $axios } = useNuxtApp()

// Filter Form Configuration
const filterFormCode = "po_register_filter"
const filterEndPoint = "/form/defaultForm"

// Table Columns
const columns = [
    { accessorKey: 'po_number', header: 'PO Number' },
    { accessorKey: 'po_date', header: 'PO Date' },
    { accessorKey: 'vendor', header: 'Vendor' },
    { accessorKey: 'generated_by', header: 'Generated by' },
    { accessorKey: 'type', header: 'Type' },
    { id: 'action'}
]

// Data
const data = ref([])

// Load data
const loadForm = async () => {
    loading.value = true
    
    try {
        const endpoint = '/form/dummy'
         
        const dataSchema = {
            po_number: 'TEXT',
            po_date: 'DATE',
            vendor: 'TEXT',
            generated_by: 'TEXT',
            type: 'TEXT',
        }
        
        const result = await $axios.post(endpoint, { schema: dataSchema })
        data.value = result.data.data || []
        
    } catch (err) {
        error.value = err.response?.data?.message || err.message || 'Failed to load data'
        console.error('Error loading PO register:', err)
    } finally {
        loading.value = false
    }
}

// Initialize
onMounted(loadForm)



</script>

